### ISSUE TITLE
Web not connecting to the db on docker

### ISSUE THREAD

**Issue by pjmoura577** [DarkflameUniverse/NexusDashboard#92] opened 2024-01-11 00:28 UTC
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/64061583/183412e7-ca51-4482-ae30-0e9ddcedd96c)
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/64061583/a4b8c942-e41c-4581-b5f9-b4f06706705e)

**Comment by Xiphoseer** [comment] 2024-01-11 00:47
Are there more logs? In theory this only happens if a previous migration crashed after creating the notes column

**Comment by PlatinPython** [comment] 2024-01-27 11:26
I've run into the same error. The following steps are what I did to arrive there:

1. Install Docker Desktop and move the client to the `client` subfolder
2. Download `docker-compose.yml` and `.env.example` (renamed to `.env`)
3. Set `ACCOUNT_MANAGER_SECRET` to a "SHA 256-bit Key" and `MARIADB_PASSWORD` to a passphrase containing only `a-z` and `-`
4. Run `docker compose up -d` in the folder containing `client`, `docker-compose.yml` and `.env`
5. Start the `dlu-darkflameserver-1` container again (It stops for some reason)
6. Run `docker exec -it dlu-darkflameserver-1 /app/MasterServer -a`
7. Try to log in via the Nexus Dashboard (This leads to an internal server error)
8. Try to manually run `flask db upgrade` in the `dlu-darkflameweb-1` container.

Logs: https://gist.github.com/PlatinPython/59a8c9c14d7904c1424cc377a003f789

**Comment by Xiphoseer** [comment] 2024-01-27 20:08
Hi @PlatinPython thank you very much for the detailed report. Based on the errors in the logs, I think you may be hitting https://github.com/MariaDB/mariadb-docker/issues/331 (aka https://jira.mariadb.org/browse/MDEV-24189, aka https://github.com/microsoft/WSL/issues/8443), which explains why I can't reproduce it on linux. Can you check whether the reproduction in https://github.com/microsoft/WSL/issues/8443#issuecomment-1836812926 applies to you?

**Comment by PlatinPython** [comment] 2024-01-27 20:26
As far as I can tell, the reproduction linked does not apply to me, as I don't get `error on fstat errno 2` anywhere in my output.
I had already added the details of my docker setup to my original comment. I'll give the Hyper-V backend a try and report back.

**Comment by PlatinPython** [comment] 2024-01-27 20:47
Docker with the Hyper-V backend seems to work fine. Login works and `flask db upgrade` also runs without errors.

**Comment by aronwk-aaron** [comment] 2024-10-11 03:20
closing as resolved

**Closed by aronwk-aaron** 2024-10-11 03:20 UTC
